puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witched of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# Total number of students added to one line
print "Overall, we have "
print 11
puts " great students"