student_count = 11
puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witched of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# Total number of students added to one line using string interpolation.
puts "Overall, we have #{student_count} great students"